// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/src/domain/use_cases/login/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness_app/core/common/apis/api_result.dart' as _i4;
import 'package:super_fitness_app/src/data/api/core/api_request_models/edit_profile_request/edit_profile_request.dart'
    as _i14;
import 'package:super_fitness_app/src/data/api/core/api_request_models/register/register_request_model.dart'
    as _i13;
import 'package:super_fitness_app/src/domain/entities/app_user_entity/app_user_entity.dart'
    as _i12;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/forget_password_request_entity.dart'
    as _i6;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/forget_password_response_entity.dart'
    as _i5;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/reset_password_request_entity.dart'
    as _i11;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/reset_password_response_entity.dart'
    as _i10;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/verify_reset_code_request_entity.dart'
    as _i9;
import 'package:super_fitness_app/src/domain/entities/auth/forget_password/verify_reset_code_response_entity.dart'
    as _i8;
import 'package:super_fitness_app/src/domain/entities/auth/logout_entity.dart'
    as _i16;
import 'package:super_fitness_app/src/domain/repositories/auth/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>> forgetPassword(
          _i6.ForgetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.ForgetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.VerifyResetCodeResponseEntity>> verifyResetCode(
          _i9.VerifyResetCodeRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [request],
        ),
        returnValue: _i3
            .Future<_i4.ApiResult<_i8.VerifyResetCodeResponseEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i8.VerifyResetCodeResponseEntity>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.VerifyResetCodeResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.ResetPasswordResponseEntity>> resetPassword(
          _i11.ResetPasswordRequestEntity? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i10.ResetPasswordResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i10.ResetPasswordResponseEntity>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i10.ResetPasswordResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<void>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.ApiResult<void>>.value(
            _i7.dummyValue<_i4.ApiResult<void>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<void>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.AppUserEntity>> register(
          {required _i13.RegisterRequestModel? registerRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#registerRequest: registerRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i12.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i12.AppUserEntity>>(
          this,
          Invocation.method(
            #register,
            [],
            {#registerRequest: registerRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.AppUserEntity?>> getUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i12.AppUserEntity?>>.value(
            _i7.dummyValue<_i4.ApiResult<_i12.AppUserEntity?>>(
          this,
          Invocation.method(
            #getUserData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.AppUserEntity?>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.AppUserEntity>> editProfile(
          {required _i14.EditProfileRequest? editProfileRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [],
          {#editProfileRequest: editProfileRequest},
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i12.AppUserEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i12.AppUserEntity>>(
          this,
          Invocation.method(
            #editProfile,
            [],
            {#editProfileRequest: editProfileRequest},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.AppUserEntity>>);

  @override
  _i3.Future<_i4.ApiResult<String>> uploadImage({required _i15.File? image}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [],
          {#image: image},
        ),
        returnValue: _i3.Future<_i4.ApiResult<String>>.value(
            _i7.dummyValue<_i4.ApiResult<String>>(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {#image: image},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<String>>);

  @override
  _i3.Future<_i4.ApiResult<_i16.LogoutEntity>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i16.LogoutEntity>>.value(
            _i7.dummyValue<_i4.ApiResult<_i16.LogoutEntity>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i16.LogoutEntity>>);
}
