// Mocks generated by Mockito 5.4.5 from annotations
// in super_fitness_app/test/src/data/data_source/online_data_source/auth/auth_online_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/src/data/api/api_services.dart' as _i8;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/forget_password_request_model.dart'
    as _i10;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/reset_password_request_model.dart'
    as _i12;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/verify_reset_code_request_model.dart'
    as _i11;
import 'package:super_fitness_app/src/data/api/core/api_request_models/login/login_request.dart'
    as _i13;
import 'package:super_fitness_app/src/data/api/core/api_request_models/register/register_request_model.dart'
    as _i14;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/forget_password_response_model.dart'
    as _i2;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/reset_password_response_model.dart'
    as _i4;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/verify_reset_code_response_model.dart'
    as _i3;
import 'package:super_fitness_app/src/data/api/core/api_response_models/login/login_response.dart'
    as _i5;
import 'package:super_fitness_app/src/data/api/core/api_response_models/register/register_response_model.dart'
    as _i6;
import 'package:super_fitness_app/src/domain/entities/app_user_entity/app_user_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseModel_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseModel {
  _FakeForgetPasswordResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseModel_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseModel {
  _FakeVerifyResetCodeResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseModel {
  _FakeResetPasswordResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_3 extends _i1.SmartFake implements _i5.LoginResponse {
  _FakeLoginResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponseModel_4 extends _i1.SmartFake
    implements _i6.RegisterResponseModel {
  _FakeRegisterResponseModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUserEntity_5 extends _i1.SmartFake implements _i7.AppUserEntity {
  _FakeAppUserEntity_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i8.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ForgetPasswordResponseModel> forgetPassword(
    _i10.ForgetPasswordRequestModel? forgetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestModel]),
            returnValue: _i9.Future<_i2.ForgetPasswordResponseModel>.value(
              _FakeForgetPasswordResponseModel_0(
                this,
                Invocation.method(#forgetPassword, [
                  forgetPasswordRequestModel,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.ForgetPasswordResponseModel>);

  @override
  _i9.Future<_i3.VerifyResetCodeResponseModel> verifyResetCode(
    _i11.VerifyResetCodeRequestModel? verifyResetCodeRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestModel]),
            returnValue: _i9.Future<_i3.VerifyResetCodeResponseModel>.value(
              _FakeVerifyResetCodeResponseModel_1(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestModel,
                ]),
              ),
            ),
          )
          as _i9.Future<_i3.VerifyResetCodeResponseModel>);

  @override
  _i9.Future<_i4.ResetPasswordResponseModel> resetPassword(
    _i12.ResetPasswordRequestModel? resetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestModel]),
            returnValue: _i9.Future<_i4.ResetPasswordResponseModel>.value(
              _FakeResetPasswordResponseModel_2(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestModel]),
              ),
            ),
          )
          as _i9.Future<_i4.ResetPasswordResponseModel>);

  @override
  _i9.Future<_i5.LoginResponse> login(_i13.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequest]),
            returnValue: _i9.Future<_i5.LoginResponse>.value(
              _FakeLoginResponse_3(
                this,
                Invocation.method(#login, [loginRequest]),
              ),
            ),
          )
          as _i9.Future<_i5.LoginResponse>);

  @override
  _i9.Future<_i6.RegisterResponseModel> register({
    required _i14.RegisterRequestModel? registerRequestModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #registerRequestModel: registerRequestModel,
            }),
            returnValue: _i9.Future<_i6.RegisterResponseModel>.value(
              _FakeRegisterResponseModel_4(
                this,
                Invocation.method(#register, [], {
                  #registerRequestModel: registerRequestModel,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.RegisterResponseModel>);
}

/// A class which mocks [AppUserEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppUserEntity extends _i1.Mock implements _i7.AppUserEntity {
  MockAppUserEntity() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [RegisterRequestModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterRequestModel extends _i1.Mock
    implements _i14.RegisterRequestModel {
  MockRegisterRequestModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set firstName(String? _firstName) => super.noSuchMethod(
    Invocation.setter(#firstName, _firstName),
    returnValueForMissingStub: null,
  );

  @override
  set lastName(String? _lastName) => super.noSuchMethod(
    Invocation.setter(#lastName, _lastName),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? _email) => super.noSuchMethod(
    Invocation.setter(#email, _email),
    returnValueForMissingStub: null,
  );

  @override
  set password(String? _password) => super.noSuchMethod(
    Invocation.setter(#password, _password),
    returnValueForMissingStub: null,
  );

  @override
  set rePassword(String? _rePassword) => super.noSuchMethod(
    Invocation.setter(#rePassword, _rePassword),
    returnValueForMissingStub: null,
  );

  @override
  set gender(String? _gender) => super.noSuchMethod(
    Invocation.setter(#gender, _gender),
    returnValueForMissingStub: null,
  );

  @override
  set height(num? _height) => super.noSuchMethod(
    Invocation.setter(#height, _height),
    returnValueForMissingStub: null,
  );

  @override
  set weight(num? _weight) => super.noSuchMethod(
    Invocation.setter(#weight, _weight),
    returnValueForMissingStub: null,
  );

  @override
  set age(num? _age) => super.noSuchMethod(
    Invocation.setter(#age, _age),
    returnValueForMissingStub: null,
  );

  @override
  set goal(String? _goal) => super.noSuchMethod(
    Invocation.setter(#goal, _goal),
    returnValueForMissingStub: null,
  );

  @override
  set activityLevel(String? _activityLevel) => super.noSuchMethod(
    Invocation.setter(#activityLevel, _activityLevel),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [RegisterResponseModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterResponseModel extends _i1.Mock
    implements _i6.RegisterResponseModel {
  MockRegisterResponseModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i7.AppUserEntity toAppUserEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toAppUserEntity, []),
            returnValue: _FakeAppUserEntity_5(
              this,
              Invocation.method(#toAppUserEntity, []),
            ),
          )
          as _i7.AppUserEntity);
}

/// A class which mocks [LoginResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginResponse extends _i1.Mock implements _i5.LoginResponse {
  MockLoginResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [LoginRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRequest extends _i1.Mock implements _i13.LoginRequest {
  MockLoginRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
