// Mocks generated by Mockito 5.4.5 from annotations
// in super_fitness_app/test/src/data/repositories_impl/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/forget_password_request_model.dart'
    as _i9;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/reset_password_request_model.dart'
    as _i11;
import 'package:super_fitness_app/src/data/api/core/api_request_models/forget_password/verify_reset_code_request_model.dart'
    as _i10;
import 'package:super_fitness_app/src/data/api/core/api_request_models/login/login_request.dart'
    as _i12;
import 'package:super_fitness_app/src/data/api/core/api_request_models/register/register_request_model.dart'
    as _i13;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/forget_password_response_model.dart'
    as _i2;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/reset_password_response_model.dart'
    as _i4;
import 'package:super_fitness_app/src/data/api/core/api_response_models/forget_password/verify_reset_code_response_model.dart'
    as _i3;
import 'package:super_fitness_app/src/data/api/core/api_response_models/login/login_response.dart'
    as _i5;
import 'package:super_fitness_app/src/data/data_source/offline_data_source/auth/auth_offline_data_source/auth_offline_data_source.dart'
    as _i15;
import 'package:super_fitness_app/src/data/data_source/online_data_source/auth/auth_online_data_source.dart'
    as _i7;
import 'package:super_fitness_app/src/domain/entities/app_user_entity/app_user_entity.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponseModel_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponseModel {
  _FakeForgetPasswordResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponseModel_1 extends _i1.SmartFake
    implements _i3.VerifyResetCodeResponseModel {
  _FakeVerifyResetCodeResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponseModel {
  _FakeResetPasswordResponseModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_3 extends _i1.SmartFake implements _i5.LoginResponse {
  _FakeLoginResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUserEntity_4 extends _i1.SmartFake implements _i6.AppUserEntity {
  _FakeAppUserEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthOnlineDataSource extends _i1.Mock
    implements _i7.AuthOnlineDataSource {
  MockAuthOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.ForgetPasswordResponseModel> forgetPassword(
    _i9.ForgetPasswordRequestModel? forgetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequestModel]),
            returnValue: _i8.Future<_i2.ForgetPasswordResponseModel>.value(
              _FakeForgetPasswordResponseModel_0(
                this,
                Invocation.method(#forgetPassword, [
                  forgetPasswordRequestModel,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.ForgetPasswordResponseModel>);

  @override
  _i8.Future<_i3.VerifyResetCodeResponseModel> verifyResetCode(
    _i10.VerifyResetCodeRequestModel? verifyResetCodeRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [verifyResetCodeRequestModel]),
            returnValue: _i8.Future<_i3.VerifyResetCodeResponseModel>.value(
              _FakeVerifyResetCodeResponseModel_1(
                this,
                Invocation.method(#verifyResetCode, [
                  verifyResetCodeRequestModel,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.VerifyResetCodeResponseModel>);

  @override
  _i8.Future<_i4.ResetPasswordResponseModel> resetPassword(
    _i11.ResetPasswordRequestModel? resetPasswordRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestModel]),
            returnValue: _i8.Future<_i4.ResetPasswordResponseModel>.value(
              _FakeResetPasswordResponseModel_2(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestModel]),
              ),
            ),
          )
          as _i8.Future<_i4.ResetPasswordResponseModel>);

  @override
  _i8.Future<_i5.LoginResponse> login(_i12.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequest]),
            returnValue: _i8.Future<_i5.LoginResponse>.value(
              _FakeLoginResponse_3(
                this,
                Invocation.method(#login, [loginRequest]),
              ),
            ),
          )
          as _i8.Future<_i5.LoginResponse>);

  @override
  _i8.Future<(_i6.AppUserEntity, String)> register(
    _i13.RegisterRequestModel? registerRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequest]),
            returnValue: _i8.Future<(_i6.AppUserEntity, String)>.value((
              _FakeAppUserEntity_4(
                this,
                Invocation.method(#register, [registerRequest]),
              ),
              _i14.dummyValue<String>(
                this,
                Invocation.method(#register, [registerRequest]),
              ),
            )),
          )
          as _i8.Future<(_i6.AppUserEntity, String)>);
}

/// A class which mocks [AuthOfflineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthOfflineDataSource extends _i1.Mock
    implements _i15.AuthOfflineDataSource {
  MockAuthOfflineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveToken({String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [], {#token: token}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i8.Future<String>);
}

/// A class which mocks [LoginResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginResponse extends _i1.Mock implements _i5.LoginResponse {
  MockLoginResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
