// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/src/domain/use_cases/workouts/muscles_group_use_case.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness_app/core/common/apis/api_result.dart' as _i4;
import 'package:super_fitness_app/src/domain/entities/workouts/exercises_entity.dart'
    as _i8;
import 'package:super_fitness_app/src/domain/entities/workouts/muscle_entity.dart'
    as _i7;
import 'package:super_fitness_app/src/domain/entities/workouts/muscles_group_entity.dart'
    as _i5;
import 'package:super_fitness_app/src/domain/repositories/workouts/workouts_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutsRepository extends _i1.Mock
    implements _i2.WorkoutsRepository {
  MockWorkoutsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.MusclesGroupEntity>>> getMusclesGroup() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMusclesGroup,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<List<_i5.MusclesGroupEntity>>>.value(
                _i6.dummyValue<_i4.ApiResult<List<_i5.MusclesGroupEntity>>>(
          this,
          Invocation.method(
            #getMusclesGroup,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.MusclesGroupEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i7.MusclesEntity>>> getFullBodyMuscles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullBodyMuscles,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i7.MusclesEntity>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i7.MusclesEntity>>>(
          this,
          Invocation.method(
            #getFullBodyMuscles,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i7.MusclesEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>> getExercisesByMuscleId(
          String? muscleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByMuscleId,
          [muscleId],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i8.ExerciseEntity>>>(
          this,
          Invocation.method(
            #getExercisesByMuscleId,
            [muscleId],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>> getAllExercises() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExercises,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i8.ExerciseEntity>>>(
          this,
          Invocation.method(
            #getAllExercises,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>> getExercisesByMuscleId(
          String? muscleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesByMuscleId,
          [muscleId],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i8.ExerciseEntity>>>(
          this,
          Invocation.method(
            #getExercisesByMuscleId,
            [muscleId],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>);
}
